# 工作流名称：手动触发EZ-Clean打包发布（已修复Git身份错误）
name: EZ-Clean-Manual-Release

# 仅支持手动触发，需输入版本号
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: '输入发布版本号（格式：v+数字，例：v1.0.1）'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  manual-build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取仓库代码
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 步骤2：验证版本号格式
      - name: 验证版本号格式
        run: |
          if ! [[ ${{ github.event.inputs.release_version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "错误：版本号格式不正确！需符合 v主版本.次版本.修订号（例：v1.0.1）"
            exit 1
          fi
          echo "版本号格式验证通过：${{ github.event.inputs.release_version }}"

      # 步骤3：检查Tag是否已存在
      - name: 检查Tag是否已存在
        run: |
          TAG=${{ github.event.inputs.release_version }}
          if git rev-parse --verify --quiet $TAG; then
            echo "错误：Tag $TAG 已存在！请更换版本号（如v1.0.2）"
            exit 1
          fi
          echo "Tag $TAG 不存在，可正常创建"

      # 【新增】步骤4：配置Git提交者身份（解决身份未知错误）
      - name: 配置Git全局身份
        run: |
          # 使用GitHub Actions默认的Actor信息（仓库操作人）作为Git身份
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          echo "Git身份配置完成：用户名=${{ github.actor }}，邮箱=${{ github.actor }}@users.noreply.github.com"

      # 步骤5：创建并推送Tag（现在身份已配置，不会报错）
      - name: 创建并推送Tag
        run: |
          TAG=${{ github.event.inputs.release_version }}
          git tag -a $TAG -m "EZ-Clean手动发布 $TAG（触发时间：$(date +'%Y-%m-%d %H:%M:%S')）"
          git push origin $TAG
          echo "Tag $TAG 已创建并推送成功"

      # 步骤6：打包为EZ-Clean.zip
      - name: 打包为EZ-Clean.zip
        run: |
          cd $GITHUB_WORKSPACE
          zip -r EZ-Clean.zip . -x ".git/*" ".github/*" "node_modules/*"
          echo "ZIP包打包完成：EZ-Clean.zip"

      # 步骤7：创建GitHub Release
      - name: 创建GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: EZ-Clean-${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false

      # 步骤8：上传ZIP包到Release
      - name: 上传ZIP包到Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/EZ-Clean.zip
          asset_name: EZ-Clean.zip
          asset_content_type: application/zip
